#!/usr/bin/env node

/**
 * Local CI Simulator — mirrors the GitHub Actions workflow.
 *
 * This script simulates what happens when the GitHub Action triggers:
 *   1. Receives a trigger event (manual dispatch, issue labeled, etc.)
 *   2. Reads .agents/config.yaml to determine which agent to run
 *   3. Runs the agent
 *   4. Commits output to a new branch (or current branch)
 *   5. Shows what a PR would look like
 *
 * Usage:
 *   node dist/simulate-ci.js --repo /path/to/repo --trigger manual
 *   node dist/simulate-ci.js --repo /path/to/repo --trigger issue_labeled --label agent:docs
 *
 * This produces identical output to the real GitHub Action, so when
 * you push to GitHub, the workflow just works.
 */

import * as fs from "fs";
import * as path from "path";
import * as child_process from "child_process";
import { loadAgentsConfig, scanRepo, assembleContext } from "@sdlc-agents/core";
import { runContextBuilder } from "./index";

// ── ANSI colors for pretty output ──
const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  cyan: "\x1b[36m",
  red: "\x1b[31m",
  bgBlue: "\x1b[44m",
  bgGreen: "\x1b[42m",
  white: "\x1b[37m",
};

function banner(text: string): void {
  const line = "═".repeat(60);
  console.log(`\n${c.cyan}${line}${c.reset}`);
  console.log(`${c.cyan}║${c.reset} ${c.bold}${text}${c.reset}`);
  console.log(`${c.cyan}${line}${c.reset}\n`);
}

function step(num: number, total: number, text: string): void {
  console.log(`${c.blue}[Step ${num}/${total}]${c.reset} ${c.bold}${text}${c.reset}`);
}

function success(text: string): void {
  console.log(`${c.green}  ✅ ${text}${c.reset}`);
}

function warn(text: string): void {
  console.log(`${c.yellow}  ⚠️  ${text}${c.reset}`);
}

function info(text: string): void {
  console.log(`${c.dim}     ${text}${c.reset}`);
}

function ciLog(text: string): void {
  console.log(`${c.dim}  │ ${text}${c.reset}`);
}

function shell(cmd: string, cwd: string): string {
  try {
    return child_process.execSync(cmd, { cwd, encoding: "utf-8", stdio: "pipe" }).trim();
  } catch {
    return "";
  }
}

// ── Arg parsing ──

function parseArgs(): Record<string, string> {
  const args: Record<string, string> = {};
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      const key = argv[i].replace("--", "");
      const value = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[i + 1] : "true";
      args[key] = value;
      if (value !== "true") i++;
    }
  }
  return args;
}

// ── Simulate Git operations ──

function simulateGitBranch(repoRoot: string): string {
  const branchName = `agent/context-builder-${Date.now()}`;
  const isGitRepo = fs.existsSync(path.join(repoRoot, ".git"));

  if (isGitRepo) {
    const currentBranch = shell("git branch --show-current", repoRoot);
    ciLog(`Current branch: ${currentBranch}`);
    ciLog(`Would create branch: ${branchName}`);
  } else {
    ciLog("Not a git repo — skipping branch creation (will write to working dir)");
  }

  return branchName;
}

function simulateGitCommit(repoRoot: string, branchName: string, files: string[]): void {
  const isGitRepo = fs.existsSync(path.join(repoRoot, ".git"));

  if (isGitRepo) {
    ciLog("Staging generated files...");
    for (const f of files) {
      ciLog(`  git add ${f}`);
    }
    ciLog(`Commit: [agent] Update context documentation`);
    ciLog(`Branch: ${branchName}`);
    ciLog("");
    ciLog("To actually commit, run:");
    ciLog(`  cd ${repoRoot}`);
    ciLog(`  git checkout -b ${branchName}`);
    ciLog(`  git add .agents/docs/`);
    ciLog(`  git commit -m "[agent] Update context documentation"`);
    ciLog(`  git push origin ${branchName}`);
  } else {
    ciLog("Files written to working directory (no git operations)");
  }
}

function simulatePR(repoRoot: string, branchName: string, files: string[]): void {
  console.log("");
  console.log(`${c.bgGreen}${c.white} PULL REQUEST PREVIEW ${c.reset}`);
  console.log("");
  console.log(`  ${c.bold}Title:${c.reset}  [Agent] Update context documentation`);
  console.log(`  ${c.bold}Branch:${c.reset} ${branchName} → main`);
  console.log(`  ${c.bold}Labels:${c.reset} 🤖 ai-generated, needs-review`);
  console.log(`  ${c.bold}Files:${c.reset}`);
  for (const f of files) {
    const fullPath = path.join(repoRoot, f);
    if (fs.existsSync(fullPath)) {
      const size = fs.statSync(fullPath).size;
      console.log(`    ${c.green}+ ${f}${c.reset} ${c.dim}(${size} bytes)${c.reset}`);
    }
  }
  console.log("");
  console.log(`  ${c.bold}Body:${c.reset}`);
  console.log(`  ${c.dim}Auto-generated by the SDLC Context Builder agent.${c.reset}`);
  console.log(`  ${c.dim}Please review the generated documentation for accuracy.${c.reset}`);
  console.log(`  ${c.dim}${c.reset}`);
  console.log(`  ${c.dim}### Files generated${c.reset}`);
  for (const f of files) {
    console.log(`  ${c.dim}- \`${f}\`${c.reset}`);
  }
}

// ── Main ──

async function main(): Promise<void> {
  const args = parseArgs();

  if (!args.repo) {
    console.error(`
${c.bold}SDLC Agent Platform — Local CI Simulator${c.reset}

Simulates the GitHub Actions workflow locally, step by step.

${c.bold}Usage:${c.reset}
  npx ts-node simulate-ci.ts --repo /path/to/repo
  node dist/simulate-ci.js --repo /path/to/repo

${c.bold}Options:${c.reset}
  --repo        Path to target repository (REQUIRED)
  --trigger     Trigger type: manual, issue_labeled, schedule (default: manual)
  --label       Issue label (for issue_labeled trigger, default: agent:docs)
  --model       Model override (default: from config.yaml or claude-sonnet-4-20250514)
  --skip-model  Skip the actual model call (shows everything except AI output)

${c.bold}Environment:${c.reset}
  ANTHROPIC_API_KEY   Required unless --skip-model is used

${c.bold}Examples:${c.reset}
  # Full simulation with AI
  export ANTHROPIC_API_KEY=sk-ant-...
  node dist/simulate-ci.js --repo ../my-project

  # Dry simulation (no API cost)
  node dist/simulate-ci.js --repo ../my-project --skip-model
`);
    process.exit(1);
  }

  const repoRoot = path.resolve(args.repo);
  const platformRoot = path.resolve(args.platform ?? path.join(__dirname, "..", "..", ".."));
  const trigger = args.trigger ?? "manual";
  const label = args.label ?? "agent:docs";
  const skipModel = args["skip-model"] === "true";
  const modelOverride = args.model;

  if (!fs.existsSync(repoRoot)) {
    console.error(`${c.red}Error: Repo not found: ${repoRoot}${c.reset}`);
    process.exit(1);
  }

  const totalSteps = skipModel ? 5 : 7;

  // ════════════════════════════════════════
  banner("SDLC Agent Platform — CI Simulation");
  console.log(`  ${c.bold}Repo:${c.reset}     ${repoRoot}`);
  console.log(`  ${c.bold}Trigger:${c.reset}  ${trigger}${trigger === "issue_labeled" ? ` (label: ${label})` : ""}`);
  console.log(`  ${c.bold}Mode:${c.reset}     ${skipModel ? "DRY RUN (no API call)" : "FULL RUN (calling Claude)"}`);
  console.log("");

  // Step 1: Simulate trigger event
  step(1, totalSteps, "Trigger received");
  if (trigger === "manual") {
    ciLog("Event: workflow_dispatch");
    ciLog("Actor: developer (manual trigger from GitHub UI)");
    ciLog("Input: agent = context-builder");
  } else if (trigger === "issue_labeled") {
    ciLog(`Event: issues.labeled`);
    ciLog(`Label: ${label}`);
    ciLog("Matching agent trigger: context-builder → issue_labeled:agent:docs");
  } else if (trigger === "schedule") {
    ciLog("Event: schedule (cron: 0 6 * * 1)");
    ciLog("Matching agent trigger: context-builder → schedule:weekly");
  }
  success("Trigger matched");

  // Step 2: Checkout + setup
  step(2, totalSteps, "Checkout repository");
  ciLog(`actions/checkout@v4 → ${repoRoot}`);
  ciLog("actions/setup-node@v4 → Node.js 20");

  // Ensure .agents/ exists with config
  const agentsDir = path.join(repoRoot, ".agents");
  const agentsConfigFile = path.join(agentsDir, "config.yaml");
  if (!fs.existsSync(agentsConfigFile)) {
    ciLog("No .agents/config.yaml found — creating with sample config...");
    fs.mkdirSync(path.join(agentsDir, "docs"), { recursive: true });
    const sampleConfig = path.join(platformRoot, "sample-agents-dir", "config.yaml");
    if (fs.existsSync(sampleConfig)) {
      fs.copyFileSync(sampleConfig, agentsConfigFile);
    }
    const sampleContext = path.join(platformRoot, "sample-agents-dir", "context.yaml");
    const targetContext = path.join(agentsDir, "context.yaml");
    if (fs.existsSync(sampleContext) && !fs.existsSync(targetContext)) {
      fs.copyFileSync(sampleContext, targetContext);
    }
    const sampleStack = path.join(platformRoot, "sample-agents-dir", "stack-profile.yaml");
    const targetStack = path.join(agentsDir, "stack-profile.yaml");
    if (fs.existsSync(sampleStack) && !fs.existsSync(targetStack)) {
      fs.copyFileSync(sampleStack, targetStack);
    }
    success("Created .agents/ directory with sample config");
  } else {
    success("Found .agents/ directory");
  }

  // Step 3: Load config
  step(3, totalSteps, "Load agent configuration");
  let config: ReturnType<typeof loadAgentsConfig> | null;
  try {
    config = loadAgentsConfig(repoRoot);
    ciLog(`Models — primary: ${config.models.primary}, fallback: ${config.models.fallback ?? "none"}`);
    ciLog(`Runtime: ${config.runtime?.type ?? "github-actions"}`);
    const enabledAgents = Object.entries(config.agents ?? {})
      .filter(([_, v]) => v.enabled)
      .map(([k]) => k);
    ciLog(`Enabled agents: ${enabledAgents.join(", ") || "none"}`);
    success("Configuration loaded");
  } catch (err) {
    warn(`Could not load config: ${err instanceof Error ? err.message : err}`);
    ciLog("Using defaults...");
    config = null;
  }

  // Step 4: Scan repository
  step(4, totalSteps, "Scan repository structure");
  const scan = scanRepo(repoRoot);
  ciLog(`Files: ${scan.totalFiles} | Dirs: ${scan.totalDirectories}`);
  ciLog(`Languages: ${scan.languages.map(l => `${l.language} (${l.percentage}%)`).join(", ") || "none detected"}`);
  ciLog(`Frameworks: ${scan.frameworks.join(", ") || "none detected"}`);
  ciLog(`Manifests: ${scan.packageManifests.length} | Config files: ${scan.configFiles.length}`);
  ciLog(`Sampled: ${scan.sampledFiles.length} files for analysis`);
  success("Repository scanned");

  // Step 5: Assemble context
  step(5, totalSteps, "Assemble layered context");
  let context;
  try {
    context = assembleContext(repoRoot, platformRoot);
    ciLog(`Org defaults: ${Object.keys(context.orgDefaults).length} keys`);
    ciLog(`Stack profile: ${Object.keys(context.stackProfile).length} keys`);
    ciLog(`Repo overrides: ${Object.keys(context.repoOverrides).length} keys`);
    ciLog(`Merged context: ${Object.keys(context.merged).length} keys`);
    success("Context assembled");
  } catch {
    ciLog("No existing context — starting fresh");
    context = null;
  }

  if (skipModel) {
    // Show what would happen
    console.log("");
    console.log(`${c.bgBlue}${c.white} DRY RUN COMPLETE ${c.reset}`);
    console.log("");
    console.log(`  The scanner found ${scan.totalFiles} files across ${scan.totalDirectories} directories.`);
    console.log(`  It would send ~${scan.sampledFiles.length} sampled files + ${scan.packageManifests.length} manifests to Claude.`);
    console.log("");
    console.log(`  ${c.bold}To run with the actual AI model:${c.reset}`);
    console.log(`  export ANTHROPIC_API_KEY=sk-ant-...`);
    console.log(`  node dist/simulate-ci.js --repo ${args.repo}`);
    console.log("");
    return;
  }

  // Step 6: Run Context Builder agent
  step(6, totalSteps, "Run Context Builder agent (calling Claude)");
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error(`${c.red}  Error: ANTHROPIC_API_KEY not set. Use --skip-model for dry run.${c.reset}`);
    process.exit(1);
  }

  const model = modelOverride
    ?? config?.agents?.["context-builder"]?.model === "fast"
      ? (config?.models?.fast ?? "claude-sonnet-4-20250514")
      : (config?.models?.primary ?? "claude-sonnet-4-20250514");

  const resolvedModel = (() => {
    if (modelOverride) return modelOverride;
    if (!config) return "claude-sonnet-4-20250514";
    const agentModelRef = config.agents?.["context-builder"]?.model ?? "fast";
    const modelsMap: Record<string, string | undefined> = {
      primary: config.models.primary,
      fallback: config.models.fallback,
      fast: config.models.fast,
    };
    return modelsMap[agentModelRef] ?? config.models.primary ?? "claude-sonnet-4-20250514";
  })();

  ciLog(`Model: ${resolvedModel}`);
  ciLog("Sending repository analysis to model...");
  console.log("");

  const result = await runContextBuilder(
    repoRoot,
    platformRoot,
    resolvedModel,
    config?.models?.fallback
  );

  if (!result.success) {
    warn("Agent completed with warnings — check output above");
  }

  // Step 7: Git operations (simulate)
  step(7, totalSteps, "Commit and create pull request");
  const branchName = simulateGitBranch(repoRoot);

  const generatedFiles = result.outputs.map(o => o.path);
  simulateGitCommit(repoRoot, branchName, generatedFiles);
  simulatePR(repoRoot, branchName, generatedFiles);

  // ════════════════════════════════════════
  banner("CI Simulation Complete");
  console.log(`  ${c.bold}Agent:${c.reset}     context-builder`);
  console.log(`  ${c.bold}Status:${c.reset}    ${result.success ? `${c.green}SUCCESS${c.reset}` : `${c.yellow}PARTIAL${c.reset}`}`);
  console.log(`  ${c.bold}Files:${c.reset}     ${result.outputs.length} generated`);
  console.log(`  ${c.bold}Duration:${c.reset}  ${result.durationMs}ms`);
  console.log(`  ${c.bold}Tokens:${c.reset}    ${result.totalTokens}`);
  console.log("");
  console.log(`  ${c.bold}Generated files:${c.reset}`);
  for (const o of result.outputs) {
    console.log(`    ${c.green}+ ${path.join(repoRoot, o.path)}${c.reset}`);
  }
  console.log("");
  console.log(`  ${c.bold}Next steps:${c.reset}`);
  console.log(`    1. Review the generated docs in ${path.join(repoRoot, ".agents", "docs")}/`);
  console.log(`    2. When ready to go live, push the sdlc-agents repo to GitHub`);
  console.log(`    3. Copy .github/workflows/sdlc-agents.yml to your pilot repo`);
  console.log(`    4. Add ANTHROPIC_API_KEY to repo Secrets`);
  console.log(`    5. Trigger via Actions tab → "Run workflow"`);
  console.log("");
}

main().catch((err) => {
  console.error(`${c.red}Fatal error:${c.reset}`, err);
  process.exit(1);
});
